language: node_js
node_js:
  - lts/*
cache: npm install
addons:
  sonarcloud:
    organization: "tradetrust"
jobs:
  include:
    - stage: unit_test
      script:
        - npm run lint
        - npm run test
        - sonar-scanner
stages:
  - unit_test